name: Build and Run Dotnet WebApp

on:
  push:
    branches: [ main ]
  schedule:
    - cron: '0 * * * *'  # A cada hora

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout do código
      uses: actions/checkout@v3

    - name: Instalar o .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'

    - name: Restaurar dependências
      run: dotnet restore **/*.csproj

    - name: Compilar a aplicação
      run: dotnet build **/*.csproj --no-restore
